FROM python:3.12-slim

WORKDIR /app

RUN pip install torch==2.3.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy all project files
COPY . .

# Optional: make sure data dir exists
RUN mkdir -p /app/data

CMD ["python", "faiss-vectorstore.py"]